name: smart_home_controller
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  window_manager: ^0.5.1
  video_player: ^2.8.0
  mjpeg_stream: ^1.0.0
  provider: ^6.0.0
  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^31.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
